# Generated by Django 4.2.4 on 2023-08-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_discription_userprofile_description_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
